In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# import seaborn as sns

In [2]:
data = pd.read_csv("../data/train.csv")
data.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,534,531363010,20,RL,80.0,9605,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,159000
1,803,906203120,20,RL,90.0,14684,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,271900
2,956,916176030,20,RL,NaN,14375,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,1,2009,COD,Abnorml,137500
3,460,528180130,120,RL,48.0,6472,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,248500
4,487,528290030,80,RL,61.0,9734,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,167000

In [3]:
missing_columns = data.columns[data.isnull().any()]
print("Columns with missing values:", missing_columns)
print(len(missing_columns))

Columns with missing values: Index(['Lot Frontage', 'Alley', 'Mas Vnr Type', 'Mas Vnr Area', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Electrical', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Pool QC', 'Fence',
       'Misc Feature'],
      dtype='str')
27

In [4]:
data.fillna({"Lot Frontage": 0}, inplace=True)
data.fillna({"Mas Vnr Type": "None"}, inplace=True)
data.fillna({"Mas Vnr Area": 0}, inplace=True)
data.fillna({"Garage Type": "None"}, inplace=True)
data.fillna({"Garage Yr Blt": 0}, inplace=True)
data.fillna({"Garage Finish": "None"}, inplace=True)
data.fillna({"Garage Cars": 0}, inplace=True)
data.fillna({"Garage Area": 0}, inplace=True)
data.fillna({"Garage Qual": "None"}, inplace=True)
data.fillna({"Garage Cond": "None"}, inplace=True)
data.fillna({"Bsmt Qual": "None"}, inplace=True)
data.fillna({"Bsmt Cond": "None"}, inplace=True)
data.fillna({"Bsmt Exposure": "None"}, inplace=True)
data.fillna({"BsmtFin Type 1": "None"}, inplace=True)
data.fillna({"BsmtFin Type 2": "None"}, inplace=True)
data.fillna({"Electrical": "None"}, inplace=True)
data.fillna({"Fireplace Qu": "None"}, inplace=True)
data.fillna({"Alley": "None"}, inplace=True)
data.fillna({"Pool QC": "None"}, inplace=True)
data.fillna({"Fence": "None"}, inplace=True)
data.fillna({"Misc Feature": "None"}, inplace=True)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,534,531363010,20,RL,80.0,9605,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,159000
1,803,906203120,20,RL,90.0,14684,Pave,None,IR1,Lvl,...,0,None,None,None,0,6,2009,WD,Normal,271900
2,956,916176030,20,RL,0.0,14375,Pave,None,IR1,Lvl,...,0,None,None,None,0,1,2009,COD,Abnorml,137500
3,460,528180130,120,RL,48.0,6472,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,248500
4,487,528290030,80,RL,61.0,9734,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2009,WD,Normal,167000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,2764,906420020,60,RL,80.0,10041,Pave,None,IR1,Lvl,...,0,None,None,None,0,2,2006,WD,Abnorml,220000
2193,906,909129090,50,RH,70.0,6300,Pave,Pave,Reg,Lvl,...,0,None,None,None,0,7,2009,WD,Abnorml,160000
2194,1097,528292060,60,RL,41.0,12460,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2008,WD,Normal,225000
2195,236,905426060,30,RL,85.0,10625,Pave,None,Reg,Lvl,...,0,None,None,Shed,400,5,2010,COD,Abnorml,83000
2196,1062,528142020,60,RL,74.0,8899,Pave,None,Reg,Lvl,...,0,None,None,None,0,6,2008,WD,Normal,250000

In [5]:
data.fillna({"BsmtFin SF 1": 0}, inplace=True)
data.fillna({"BsmtFin SF 2": 0}, inplace=True)
data.fillna({"Bsmt Unf SF": 0}, inplace=True)
data.fillna({"Total Bsmt SF": 0}, inplace=True)
data.fillna({"Bsmt Full Bath": 0}, inplace=True)
data.fillna({"Bsmt Half Bath": 0}, inplace=True)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,534,531363010,20,RL,80.0,9605,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,159000
1,803,906203120,20,RL,90.0,14684,Pave,None,IR1,Lvl,...,0,None,None,None,0,6,2009,WD,Normal,271900
2,956,916176030,20,RL,0.0,14375,Pave,None,IR1,Lvl,...,0,None,None,None,0,1,2009,COD,Abnorml,137500
3,460,528180130,120,RL,48.0,6472,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,248500
4,487,528290030,80,RL,61.0,9734,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2009,WD,Normal,167000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,2764,906420020,60,RL,80.0,10041,Pave,None,IR1,Lvl,...,0,None,None,None,0,2,2006,WD,Abnorml,220000
2193,906,909129090,50,RH,70.0,6300,Pave,Pave,Reg,Lvl,...,0,None,None,None,0,7,2009,WD,Abnorml,160000
2194,1097,528292060,60,RL,41.0,12460,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2008,WD,Normal,225000
2195,236,905426060,30,RL,85.0,10625,Pave,None,Reg,Lvl,...,0,None,None,Shed,400,5,2010,COD,Abnorml,83000
2196,1062,528142020,60,RL,74.0,8899,Pave,None,Reg,Lvl,...,0,None,None,None,0,6,2008,WD,Normal,250000

In [6]:
def mapping_ordinal_data(column):
    mapping = {
        "Ex": 5,  # Excellent
        "Gd": 4,  # Good
        "TA": 3,  # Average/Typical
        "Fa": 2,  # Fair
        "Po": 1  , # Poor
    }
    
    data[column] = data[column].map(mapping)
    return data.head()

In [7]:
mapping_ordinal_data("Exter Qual")
mapping_ordinal_data("Exter Cond")
mapping_ordinal_data("Bsmt Qual")
mapping_ordinal_data("Bsmt Cond")
mapping_ordinal_data("Heating QC")
mapping_ordinal_data("Kitchen Qual")
mapping_ordinal_data("Fireplace Qu")
mapping_ordinal_data("Garage Qual")
mapping_ordinal_data("Garage Cond")

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,534,531363010,20,RL,80.0,9605,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,159000
1,803,906203120,20,RL,90.0,14684,Pave,None,IR1,Lvl,...,0,None,None,None,0,6,2009,WD,Normal,271900
2,956,916176030,20,RL,0.0,14375,Pave,None,IR1,Lvl,...,0,None,None,None,0,1,2009,COD,Abnorml,137500
3,460,528180130,120,RL,48.0,6472,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,248500
4,487,528290030,80,RL,61.0,9734,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2009,WD,Normal,167000

In [8]:
data.fillna({"Fireplace Qu": 0}, inplace=True)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,534,531363010,20,RL,80.0,9605,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,159000
1,803,906203120,20,RL,90.0,14684,Pave,None,IR1,Lvl,...,0,None,None,None,0,6,2009,WD,Normal,271900
2,956,916176030,20,RL,0.0,14375,Pave,None,IR1,Lvl,...,0,None,None,None,0,1,2009,COD,Abnorml,137500
3,460,528180130,120,RL,48.0,6472,Pave,None,Reg,Lvl,...,0,None,None,None,0,4,2009,WD,Normal,248500
4,487,528290030,80,RL,61.0,9734,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2009,WD,Normal,167000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,2764,906420020,60,RL,80.0,10041,Pave,None,IR1,Lvl,...,0,None,None,None,0,2,2006,WD,Abnorml,220000
2193,906,909129090,50,RH,70.0,6300,Pave,Pave,Reg,Lvl,...,0,None,None,None,0,7,2009,WD,Abnorml,160000
2194,1097,528292060,60,RL,41.0,12460,Pave,None,IR1,Lvl,...,0,None,None,None,0,5,2008,WD,Normal,225000
2195,236,905426060,30,RL,85.0,10625,Pave,None,Reg,Lvl,...,0,None,None,Shed,400,5,2010,COD,Abnorml,83000
2196,1062,528142020,60,RL,74.0,8899,Pave,None,Reg,Lvl,...,0,None,None,None,0,6,2008,WD,Normal,250000

In [12]:
categorical_columns = data.select_dtypes(include=['object', 'str']).columns
categorical_columns

Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
       'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
       'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Foundation',
       'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating',
       'Central Air', 'Electrical', 'Functional', 'Garage Type',
       'Garage Finish', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature',
       'Sale Type', 'Sale Condition'],
      dtype='str')

In [14]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_categorical_data = encoder.fit_transform(data[categorical_columns])

for i, column in enumerate(encoder.categories_):
    print(f"Features {i}: {encoder.categories_[i]}")

Features 0: ['A (agr)' 'C (all)' 'FV' 'I (all)' 'RH' 'RL' 'RM']
Features 1: ['Grvl' 'Pave']
Features 2: ['Grvl' 'None' 'Pave']
Features 3: ['IR1' 'IR2' 'IR3' 'Reg']
Features 4: ['Bnk' 'HLS' 'Low' 'Lvl']
Features 5: ['AllPub' 'NoSeWa' 'NoSewr']
Features 6: ['Corner' 'CulDSac' 'FR2' 'FR3' 'Inside']
Features 7: ['Gtl' 'Mod' 'Sev']
Features 8: ['Blmngtn' 'Blueste' 'BrDale' 'BrkSide' 'ClearCr' 'CollgCr' 'Crawfor'
 'Edwards' 'Gilbert' 'Greens' 'GrnHill' 'IDOTRR' 'Landmrk' 'MeadowV'
 'Mitchel' 'NAmes' 'NPkVill' 'NWAmes' 'NoRidge' 'NridgHt' 'OldTown'
 'SWISU' 'Sawyer' 'SawyerW' 'Somerst' 'StoneBr' 'Timber' 'Veenker']
Features 9: ['Artery' 'Feedr' 'Norm' 'PosA' 'PosN' 'RRAe' 'RRAn' 'RRNe' 'RRNn']
Features 10: ['Artery' 'Feedr' 'Norm' 'PosA' 'PosN' 'RRAe' 'RRAn' 'RRNn']
Features 11: ['1Fam' '2fmCon' 'Duplex' 'Twnhs' 'TwnhsE']
Features 12: ['1.5Fin' '1.5Unf' '1Story' '2.5Fin' '2.5Unf' '2Story' 'SFoyer' 'SLvl']
Features 13: ['Flat' 'Gable' 'Gambrel' 'Hip' 'Mansard' 'Shed']
Features 14: ['ClyTile' 'CompShg' 'Membran' 'Metal' 'Roll' 'Tar&Grv' 'WdShake'
 'WdShngl']
Features 15: ['AsbShng' 'AsphShn' 'BrkComm' 'BrkFace' 'CBlock' 'CemntBd' 'HdBoard'
 'ImStucc' 'MetalSd' 'Plywood' 'PreCast' 'Stone' 'Stucco' 'VinylSd'
 'Wd Sdng' 'WdShing']
Features 16: ['AsbShng' 'AsphShn' 'Brk Cmn' 'BrkFace' 'CBlock' 'CmentBd' 'HdBoard'
 'ImStucc' 'MetalSd' 'Other' 'Plywood' 'PreCast' 'Stone' 'Stucco'
 'VinylSd' 'Wd Sdng' 'Wd Shng']
Features 17: ['BrkCmn' 'BrkFace' 'CBlock' 'None' 'Stone']
Features 18: ['BrkTil' 'CBlock' 'PConc' 'Slab' 'Stone' 'Wood']
Features 19: ['Av' 'Gd' 'Mn' 'No' 'None']
Features 20: ['ALQ' 'BLQ' 'GLQ' 'LwQ' 'None' 'Rec' 'Unf']
Features 21: ['ALQ' 'BLQ' 'GLQ' 'LwQ' 'None' 'Rec' 'Unf']
Features 22: ['Floor' 'GasA' 'GasW' 'Grav' 'OthW' 'Wall']
Features 23: ['N' 'Y']
Features 24: ['FuseA' 'FuseF' 'FuseP' 'Mix' 'None' 'SBrkr']
Features 25: ['Maj1' 'Maj2' 'Min1' 'Min2' 'Mod' 'Sal' 'Sev' 'Typ']
Features 26: ['2Types' 'Attchd' 'Basment' 'BuiltIn' 'CarPort' 'Detchd' 'None']
Features 27: ['Fin' 'None' 'RFn' 'Unf']
Features 28: ['N' 'P' 'Y']
Features 29: ['Ex' 'Fa' 'Gd' 'None' 'TA']
Features 30: ['GdPrv' 'GdWo' 'MnPrv' 'MnWw' 'None']
Features 31: ['Elev' 'Gar2' 'None' 'Othr' 'Shed' 'TenC']
Features 32: ['COD' 'CWD' 'Con' 'ConLD' 'ConLI' 'ConLw' 'New' 'Oth' 'VWD' 'WD ']
Features 33: ['Abnorml' 'AdjLand' 'Alloca' 'Family' 'Normal' 'Partial']

In [16]:
print(encoded_categorical_data.shape)
print(data.shape)
print(encoded_categorical_data)

(2197, 234)
(2197, 82)
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

In [17]:
# Get feature names for the encoded data
encoded_feature_names = encoder.get_feature_names_out(categorical_columns)

# Create a DataFrame from the encoded data
encoded_df = pd.DataFrame(encoded_categorical_data, columns=encoded_feature_names, index=data.index)

# Drop the original categorical columns from data
data = data.drop(columns=categorical_columns)

# Concatenate the encoded DataFrame to the original data
data = pd.concat([data, encoded_df], axis=1)

data.head()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_Abnorml,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,534,531363010,20,80.0,9605,7,6,2007,2007,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,803,906203120,20,90.0,14684,7,7,1990,1991,234.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,956,916176030,20,0.0,14375,6,6,1958,1958,541.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,460,528180130,120,48.0,6472,9,5,2008,2008,500.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,487,528290030,80,61.0,9734,7,5,2004,2004,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
data.to_csv("../data/preprocessed_data.csv", index=False)